# Generated by Django 3.2.19 on 2023-07-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venues',
            name='event',
        ),
        migrations.AddField(
            model_name='venues',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
