# Generated by Django 3.2.19 on 2023-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=254),
        ),
    ]
