# Generated by Django 3.2.19 on 2023-06-29 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('default_email', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('billing_adress', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.CharField(blank=True, max_length=10000, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[200, None], upload_to='members/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
