# Generated by Django 3.2.19 on 2023-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
